/**
 * Guided Worker-bouncer config — generates a ready-to-fill
 * crowdsec-cloudflare-worker-bouncer daemon YAML for operators on paid
 * Workers plans or who need Turnstile-at-edge. Secrets are placeholders
 * (`<cf-token>`, `<bouncer-key>`), never pulled from storage.
 */
import type { RequestHandler } from './$types';
import { eq } from 'drizzle-orm';
import { db } from '#lib/server/db/index.ts';
import { cloudflareAccount, cloudflareZone, server } from '#lib/server/db/app.schema.ts';
import { requirePermission } from '#lib/server/roles.ts';
import { recordAudit } from '#lib/server/audit.ts';

export const GET: RequestHandler = async (event) => {
	requirePermission(event, 'configure');
	const account = await db.query.cloudflareAccount.findFirst({
		where: eq(cloudflareAccount.id, event.url.searchParams.get('account') ?? '')
	});
	if (!account) return Response.json({ error: 'Account not found' }, { status: 404 });
	const zones = await db.query.cloudflareZone.findMany({
		where: eq(cloudflareZone.accountId, account.id)
	});
	const selected = zones.filter((z) => z.selected);
	const srv = await db.query.server.findFirst({ where: eq(server.id, 'main') });

	const zoneLines = selected
		.map((z) => `    - zone_id: ${z.zoneId}\n      actions: [ban, captcha]`)
		.join('\n');

	const yaml = `# crowdsec-cloudflare-worker-bouncer — generated by bitdoze-crowdsec-dash
# Docs: https://docs.crowdsec.net/u/bouncers/cloudflare/
#
# Before running the daemon:
#   1. Issue a bouncer key:  cscli bouncers add crowdsec-dash-cloudflare
#      (or "Allowlist via agent"-style flow — the key is shown once)
#   2. Create a scoped Cloudflare token: Workers Scripts:Edit,
#      Workers KV Storage:Edit, Zone:Read, Account:Read.
#   3. IMPORTANT — worker routes are created FAIL-CLOSED by default.
#      After the daemon binds routes, switch each to fail-open in the
#      Cloudflare dashboard or an unreachable Worker blocks the site.
#   4. Quotas: Free plan = 1,000 KV writes + 100,000 Worker req/day.
#      On busy sites this exhausts fast — prefer the IP-list mode.
mode: cloudflare
cloudflare:
  account_id: ${account.cfAccountId ?? '<cf-account-id>'}
  token: <cf-token>
  zones:
${zoneLines || '    # - zone_id: <zone-id>\n    #   actions: [ban, captcha]'}
crowdsec:
  lapi_url: ${srv?.lapiUrl ?? '<lapi-url>'}
  lapi_key: <bouncer-key>
  update_frequency: 10s
  # Keep it to local origins — the community blocklist alone busts the
  # Free-plan KV quota.
  only_include_decisions_from: [cscli, crowdsec, crowdsec-appsec]
`;
	await recordAudit({
		event,
		action: 'cloudflare.workerConfig',
		detail: { accountId: account.id, zones: selected.length }
	});
	return new Response(yaml, {
		headers: {
			'content-type': 'application/yaml',
			'content-disposition': 'attachment; filename="crowdsec-cloudflare-worker-bouncer.yaml"'
		}
	});
};
